#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# run-inbox-zero.sh — Main Orchestrator
# Orchestra Intelligence — Agent World
# ═══════════════════════════════════════════════════════════════
# Usage:
#   ./run-inbox-zero.sh                  # Default: scan unread
#   ./run-inbox-zero.sh full             # Full overnight scan (18h)
#   ./run-inbox-zero.sh morning          # Pre-morning scan (12h)
#   ./run-inbox-zero.sh quick            # Quick business hours check
#   ./run-inbox-zero.sh custom "query"   # Custom Gmail query
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORTS_DIR="${HOME}/logs/inbox-zero"
DATE_SLUG=$(date +%Y-%m-%d)
START_TIME=$(date +%s)

# ── Ensure directories ──
mkdir -p "${SCRIPT_DIR}/output" "${SCRIPT_DIR}/logs" "$REPORTS_DIR"

log() {
  local msg="[$(date +%H:%M:%S)] [ORCHESTRATOR] $1"
  echo "$msg" >> "${SCRIPT_DIR}/logs/orchestrator-${DATE_SLUG}.log"
  echo "$msg" >&2
}

# ── Determine scan mode ──
MODE="${1:-default}"
case "$MODE" in
  full|overnight)
    QUERY="newer_than:18h"
    MAX_RESULTS=50
    log "Mode: FULL OVERNIGHT SCAN"
    ;;
  morning|premorning)
    QUERY="newer_than:12h"
    MAX_RESULTS=50
    log "Mode: PRE-MORNING SCAN"
    ;;
  quick|check)
    QUERY="is:unread newer_than:2h"
    MAX_RESULTS=20
    log "Mode: QUICK BUSINESS CHECK"
    ;;
  custom)
    QUERY="${2:-is:unread}"
    MAX_RESULTS="${3:-50}"
    log "Mode: CUSTOM — query: ${QUERY}"
    ;;
  *)
    QUERY="is:unread"
    MAX_RESULTS=50
    log "Mode: DEFAULT (unread)"
    ;;
esac

# ══════════════════════════════════════════════════════════════
# STEP 1: SCAN
# ══════════════════════════════════════════════════════════════
log "═══ STEP 1: Scanning emails ═══"

SCAN_OUTPUT=$("${SCRIPT_DIR}/scan-emails.sh" "$QUERY" "$MAX_RESULTS" 2>>"${SCRIPT_DIR}/logs/orchestrator-${DATE_SLUG}.log") || {
  log "ERROR: Scan failed! Check orchestrator log"
  exit 1
}

SCAN_TOTAL=$(echo "$SCAN_OUTPUT" | jq '.scan_metadata.total_emails // 0')
log "Scan complete: ${SCAN_TOTAL} emails found"

if [ "$SCAN_TOTAL" -eq 0 ]; then
  log "No emails to process. Inbox Zero achieved! 🎯"

  # Still create a summary for the record
  cat > "${SCRIPT_DIR}/output/${DATE_SLUG}-summary.md" << EOF
# 📧 Inbox Zero Report — $(date '+%Y-%m-%d %H:%M')

> **Status:** 🎯 INBOX ZERO — No unread emails!
> **Mode:** ${MODE} | **Query:** ${QUERY}

_Nothing to process. All clear._

_Generated by Inbox Zero Agent v1.0 — $(date '+%Y-%m-%d %H:%M:%S %Z')_
EOF

  exit 0
fi

# ══════════════════════════════════════════════════════════════
# STEP 2: CLASSIFY
# ══════════════════════════════════════════════════════════════
log "═══ STEP 2: Classifying emails ═══"

CLASSIFY_OUTPUT=$("${SCRIPT_DIR}/classify-emails.sh" "${SCRIPT_DIR}/output/${DATE_SLUG}-scan.json" 2>>"${SCRIPT_DIR}/logs/orchestrator-${DATE_SLUG}.log") || {
  log "ERROR: Classification failed! Check orchestrator log"
  exit 1
}

YOURS_COUNT=$(echo "$CLASSIFY_OUTPUT" | jq '.classification_metadata.yours // 0')
PREP_COUNT=$(echo "$CLASSIFY_OUTPUT" | jq '.classification_metadata.prep // 0')
DISPATCH_COUNT=$(echo "$CLASSIFY_OUTPUT" | jq '.classification_metadata.dispatch // 0')
SKIP_COUNT=$(echo "$CLASSIFY_OUTPUT" | jq '.classification_metadata.skip // 0')

log "Classification complete:"
log "  🔴 YOURS:    ${YOURS_COUNT}"
log "  🟡 PREP:     ${PREP_COUNT}"
log "  🟢 DISPATCH: ${DISPATCH_COUNT}"
log "  ⚪ SKIP:     ${SKIP_COUNT}"

# ══════════════════════════════════════════════════════════════
# STEP 3: COPY REPORT
# ══════════════════════════════════════════════════════════════
log "═══ STEP 3: Saving reports ═══"

# Copy summary to Reports directory
cp "${SCRIPT_DIR}/output/${DATE_SLUG}-summary.md" "${REPORTS_DIR}/${DATE_SLUG}-summary.md" 2>/dev/null || true

# ══════════════════════════════════════════════════════════════
# STEP 4: EXECUTION SUMMARY
# ══════════════════════════════════════════════════════════════
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

log "═══ INBOX ZERO RUN COMPLETE ═══"
log "  Duration: ${DURATION}s"
log "  Total processed: ${SCAN_TOTAL}"
log "  Reports: ${SCRIPT_DIR}/output/${DATE_SLUG}-*.{json,md}"

# ── Output event log entry (JSONL) ──
jq -n \
  --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  --arg mode "$MODE" \
  --arg query "$QUERY" \
  --argjson total "$SCAN_TOTAL" \
  --argjson yours "$YOURS_COUNT" \
  --argjson prep "$PREP_COUNT" \
  --argjson dispatch "$DISPATCH_COUNT" \
  --argjson skip "$SKIP_COUNT" \
  --argjson duration "$DURATION" \
  '{
    ts: $ts,
    type: "inbox_zero.run_complete",
    mode: $mode,
    query: $query,
    total: $total,
    yours: $yours,
    prep: $prep,
    dispatch: $dispatch,
    skip: $skip,
    duration_seconds: $duration
  }' >> "${SCRIPT_DIR}/logs/runs.jsonl"

# ── Print the human summary to stdout ──
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📧 INBOX ZERO — $(date '+%Y-%m-%d %H:%M')"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔴 YOURS:    ${YOURS_COUNT}"
echo "🟡 PREP:     ${PREP_COUNT}"
echo "🟢 DISPATCH: ${DISPATCH_COUNT}"
echo "⚪ SKIP:     ${SKIP_COUNT}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏱  ${DURATION}s | Report: output/${DATE_SLUG}-summary.md"
